export const FETCH_ALL_CATEGORIES_REQUEST = "FETCH_ALL_CATEGORIES_REQUEST";
export const FETCH_ALL_CATEGORIES_SUCESS = "FETCH_ALL_CATEGORIES_SUCCESS";
export const FETCH_ALL_CATEGORIES_FAILED = "FETCH_ALL_CATEGORIES_FAILED";

// export const FETCH_SINGLE_PRODUCT_REQUEST = "FETCH_SINGLE_PRODUCT_REQUEST";
// export const FETCH_SINGLE_PRODUCT_SUCESS = "FETCH_SINGLE_PRODUCT_SUCCESS";
// export const FETCH_SINGLE_PRODUCT_FAILED = "FETCH_SINGLE_PRODUCT_FAILED";

// export const ADD_PRODUCT_REQUEST = "ADD_PRODUCT_REQUEST";
// export const ADD_PRODUCT_SUCESS = "ADD_PRODUCT_SUCESS";
// export const ADD_PRODUCT_FAILED = "ADD_PRODUCT_FAILED";

// export const EDIT_PRODUCT_REQUEST = "EDIT_PRODUCT_REQUEST";
// export const EDIT_PRODUCT_SUCESS = "EDIT_PRODUCT_SUCESS";
// export const EDIT_PRODUCT_FAILED = "EDIT_PRODUCT_FAILED";

// export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST";
// export const DELETE_PRODUCT_SUCESS = "DELETE_PRODUCT_SUCESS";
// export const DELETE_PRODUCT_FAILED = "DELETE_PRODUCT_FAILED";

// export const FETCH_INVENTORY_REQUEST = "FETCH_INVENTORY_REQUEST";
// export const FETCH_INVENTORY_SUCESS = "FETCH_INVENTORY_SUCESS";
// export const FETCH_INVENTORY_FAILED = "FETCH_INVENTORY_FAILED";
